os:
    - linux
    - osx
language: generic
sudo: required

dist: trusty
group: edge
osx_image: xcode8.3

before_install:
    - if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew tap vapor/tap;
            brew update;
            brew install vapor redis;
            brew services start redis;
        else
            eval "$(curl -sL https://apt.vapor.sh)";
            sudo apt-get install vapor redis-server;
            sudo chmod -R a+rx /usr/;
            sudo service redis-server start;
        fi

script:
    - swift build
    - swift build -c release
    - swift test

after_success:
    - eval "$(curl -sL https://swift.vapor.sh/codecov)"
